### ISSUE TITLE
Błąd Nie ma takiego pliku ani katalogu: '/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QMapa/ui\\qmapa_dockwidget_base.ui' 

### ISSUE THREAD

**Issue by ekolabynet** [geoxyIT/QMapa#1]
Dzień dobry, 
zainstalowałem dziś wtyczkę QMapa na QGIS 3.26 na Kubuntu 22.04. Niestety zgłasza błąd, jak poniżej. 
Czy da się coś z tym zrobić ;-)?
Pozdrawiam
PM
*************

> Nie można wczytać wtyczki 'QMapa' z powodu błędu wywołania jej metody classFactory() 

FileNotFoundError: [Errno 2] Nie ma takiego pliku ani katalogu: '/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QMapa/ui\\qmapa_dockwidget_base.ui' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QMapa/__init__.py", line 39, in classFactory
    from .qmapa import QMapa
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QMapa/qmapa.py", line 41, in 
    from .qmapa_dockwidget import QMapaDockWidget
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QMapa/qmapa_dockwidget.py", line 47, in 
    FORM_CLASS, _ = uic.loadUiType(os.path.join(
  File "/usr/lib/python3/dist-packages/qgis/PyQt/uic/__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/__init__.py", line 200, in loadUiType
    winfo = compiler.UICompiler().compileUi(uifile, code_string, from_imports,
  File "/usr/lib/python3/dist-packages/PyQt5/uic/Compiler/compiler.py", line 111, in compileUi
    w = self.parse(input_stream, resource_suffix)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 1020, in parse
    document = parse(filename)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1229, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 569, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] Nie ma takiego pliku ani katalogu: '/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QMapa/ui\\qmapa_dockwidget_base.ui'

Wersja Pythona: 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] 
Wersja QGIS: 3.26.1-Buenos Aires Buenos Aires, b609df9ed4 

Lokalizacja Pythona:
/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ProcessX
/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/buffer_without_overlaps
/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/dissect_dissolve_overlaps
/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/lftools
/usr/share/qgis/python
/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python
/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/usr/local/lib/python3.10/dist-packages
/usr/lib/python3/dist-packages
/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python

**Comment by geoxyIT** [comment]
Dzień dobry!
Zwlekaliśmy z odpowiedzią na Pana błąd, z tego względu, że liczyliśmy na dodanie poprawionej wersji do repozytorium QGIS. Jednak ciągle czekamy na akceptację wersji.
W związku z tym postanowiliśmy pod linkiem: https://github.com/geoxyIT/QMapa/tree/main/wersja
dodać aktualną, poprawioną wersję 1.1.0.
Jeśli nie chce Pan czekać na akceptację od QGIS, może Pan ją pobrać i zainstalować za pomocą "instalacji z .zip".
Również bardzo prosimy o odpowiedź, czy wszystko działa prawidłowo.

**Comment by geoxyIT** [comment]
Wersja 1.1.0 jest już dostępna w repozytorium QGIS.
