### ISSUE TITLE
Wtyczka nie działa na najnowszej wersji QGISa z GDAL 3.9.0 z powodu usunięcia biblioteki ogr2ogr.py

### ISSUE THREAD

**Issue by kaszak** [geoxyIT/QMapa#3]
Jak w tytule, próba otwarcia wtyczki na QGISie z najnowszą wersją GDAL kończy się wyjątkiem ImportError, przy próbie importu biblioteki ogr2ogr z GDAL.

Biblioteka ogr2ogr została usunięta z GDAL tym commitem: https://github.com/OSGeo/gdal/commit/80e189fb37a1625003e29b6224890e0a45ef7a0c

## ŚRODOWISKO

Windows 11, najnowsza dystrybucja QGISa OSGeo4W, także wersja LTR.

$ wersja QGIS

QGIS 3.36.3 i 3.34.7 LTR,

$ wersja wtyczki QMapa
2.1.0

## RAPORT Z BŁĘDEM
```Nie można wczytać wtyczki 'QMapa' z powodu błędu wywołania jej metody classFactory() 

ImportError: cannot import name 'ogr2ogr' from 'osgeo_utils.samples' (C:\PROGRA~1\QGISlts\apps\Python312\Lib\site-packages\osgeo_utils\samples\__init__.py) 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGISlts/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/kasza/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QMapa\__init__.py", line 90, in classFactory
    from .qmapa import QMapa
  File "C:\PROGRA~1/QGISlts/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/kasza/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QMapa\qmapa.py", line 41, in 
    from .qmapa_dockwidget import QMapaDockWidget
  File "C:\PROGRA~1/QGISlts/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/kasza/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QMapa\qmapa_dockwidget.py", line 43, in 
    from .src.simple_gml_import import SimpleGmlImport
  File "C:\PROGRA~1/QGISlts/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/kasza/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QMapa\src\simple_gml_import.py", line 8, in 
    from osgeo_utils.samples import ogr2ogr
ImportError: cannot import name 'ogr2ogr' from 'osgeo_utils.samples' (C:\PROGRA~1\QGISlts\apps\Python312\Lib\site-packages\osgeo_utils\samples\__init__.py)


Wersja Pythona: 3.12.3 (main, Apr 14 2024, 17:21:43) [MSC v.1938 64 bit (AMD64)] 
Wersja QGIS: 3.34.7-Prizren Prizren, 6f7d735c 

Lokalizacja Pythona:
C:/PROGRA~1/QGISlts/apps/qgis-ltr/./python
C:/Users/kasza/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/kasza/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGISlts/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGISlts\apps\grass\grass83\etc\python
C:\Users\kasza\Documents
C:\Program Files\QGISlts\bin\python312.zip
C:\PROGRA~1\QGISlts\apps\Python312\DLLs
C:\PROGRA~1\QGISlts\apps\Python312\Lib
C:\Program Files\QGISlts\bin
C:\PROGRA~1\QGISlts\apps\Python312
C:\PROGRA~1\QGISlts\apps\Python312\Lib\site-packages
C:\PROGRA~1\QGISlts\apps\Python312\Lib\site-packages\win32
C:\PROGRA~1\QGISlts\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA~1\QGISlts\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/kasza/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\kasza\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\QMapa\external_packages
C:\Users\kasza\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\QMapa\external_packages
```

## ODTWORZENIE BŁĘDU

Zainstalować wtyczkę QMapa na najnowszej wersji QGISa dla Windows pobranej z oficjalnej strony. Na innych systemach aktualizacja GDAL do wersji co najmniej 3.9.0 także powinna sprawić ten problem.

**Comment by Kamzarr** [comment]
Naprawione w wersji 2.2.0. Niedługo wersja zostanie opublikowana.
