### ISSUE TITLE
błąd we wczytywaniu mapy egib

### ISSUE THREAD

**Issue by MagdalenaKarlikowska** [geoxyIT/QMapa#6]
mam problem z wczytaniem mapy egib, pozyskanej ze starostwa w formacie GML. Mapa zaczytuje się w 20% i potem wiesza się qgis. Błąd Pythona odsyła mnie wciąż do katalogu wtyczki:
"2024-12-12T10:09:47     WARNING    Traceback (most recent call last):
              File "C:\Users/mkarlikowska/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QMapa\qmapa_dockwidget.py", line 123, in on_pbImport_clicked
              vec_lays_list = SimpleGmlImport().runImport(name, self.progressBar, self.cmbStylization.currentText())
              File "C:\Users/mkarlikowska/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QMapa\src\simple_gml_import.py", line 393, in runImport
              loadGpkg(gpkg_path)
              File "C:\Users/mkarlikowska/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QMapa\src\load_gpkg.py", line 17, in loadGpkg
              data_layers = [lay for lay in file_data]
             TypeError: 'NoneType' object is not iterable
             "

**Comment by Kamzarr** [comment]
Problem występuje w niektórych starszych wersjach qgisa, postaramy się udostępnić poprawioną wersję wtyczki jak najszybciej. Do tego czasu proszę spróbować na wersji QGIS 3.30 lub nowszej.

**Comment by Kaemer1645** [comment]
Zmiany zostaną wprowadzone przy najbliższej aktualizacji, tak szybko jak fundacja QGIS zaakceptuje zmiany. Jeśli chce Pani już skorzystać z wtyczki na swojej wersji QGIS to zapraszam do pobrania aktualizacji stąd:

[https://github.com/geoxyIT/QMapa/tree/v2.3.1/wersja](url)
